blueprint:
  name: External Thermostat Control v1.2.1 (Integrated Safety)
  source_url: https://raw.githubusercontent.com/jcspenle/HA_SensorPilotWire/main/blueprints/automation/jcspenle/external_thermostat_control_v1.2.yaml
  description: >
    Thermostat virtuel avec SÉCURITÉ INTÉGRÉE contre les ouvertures.
    
    **Fonctionnement automatique en arrière-plan** :
    - Vérifie TOUJOURS l'état des fenêtres/portes avant d'allumer
    - IMPOSSIBLE d'allumer si un ouvrant est ouvert
    - Compatible avec le blueprint fenêtres/portes pour double sécurité
    - Hystérésis 0.5°C (optimal pour radiateurs fonte)
    
    **Architecture fail-safe** :
    - Blueprint fenêtres : Coupure immédiate à l'ouverture
    - Blueprint thermostat : Vérification avant chaque allumage
    - Résultat : Priorité ABSOLUE aux ouvertures
    
  domain: automation

  input:
    # === CONFIGURATION PRINCIPALE ===
    thermostat_active:
      name: Activation du thermostat
      description: Input boolean pour activer/désactiver le thermostat manuellement
      selector:
        entity:
          domain: input_boolean

    temperature_sensor:
      name: Capteur de température
      description: Sonde de température externe pour la régulation
      selector:
        entity:
          domain: sensor
          device_class: temperature

    temperature_setpoint:
      name: Consigne de température
      description: Input number avec la température cible
      selector:
        entity:
          domain: input_number

    hysteresis:
      name: Hystérésis
      description: Écart de température pour éviter les cycles rapides (0.5°C recommandé pour fonte)
      selector:
        number:
          min: 0.1
          max: 2.0
          step: 0.1
          unit_of_measurement: "°C"
      default: 0.5

    # === MODULE DE CHAUFFAGE ===
    module_type:
      name: Type de module chauffage
      description: "Climate: entité climate | Select: entité select fil pilote (NodOn)"
      selector:
        select:
          options: ["Climate", "Select"]
      default: "Select"

    heating_entity_climate:
      name: Entité de chauffage (Climate)
      description: "Laisser vide si type Select"
      selector:
        entity:
          domain: climate
      default: ""

    heating_entity_select:
      name: Entité de chauffage (Select Fil Pilote)
      description: "Laisser vide si type Climate"
      selector:
        entity:
          domain: select
      default: ""

    heating_mode:
      name: Mode de chauffage actif
      description: Mode à utiliser pour chauffer
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco"]
      default: "comfort"

    # === SÉCURITÉ FENÊTRES/PORTES ===
    window_sensors:
      name: Capteurs de fenêtres (optionnel mais recommandé)
      description: Le thermostat ne pourra JAMAIS allumer si fenêtre ouverte
      selector:
        entity:
          domain: binary_sensor
          device_class: window
          multiple: true
      default: []

    door_sensors:
      name: Capteurs de portes (optionnel)
      description: Le thermostat ne pourra JAMAIS allumer si porte ouverte
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true
      default: []

    sensor_logic:
      name: Logique des capteurs
      description: "Normal: on=ouvert, off=fermé | Inverse: on=fermé, off=ouvert"
      selector:
        select:
          options: ["Normal","Inverse"]
      default: "Normal"

    # === LOGS ===
    room_name:
      name: Nom de la pièce
      description: Pour identification dans les logs
      selector:
        text: {}
      default: "Pièce"

    log_entity:
      name: Entité de log (optionnel)
      description: Input_text pour logs
      selector:
        entity:
          domain: input_text
      default: ""

# ===== VARIABLES =====
variables:
  active: !input thermostat_active
  temp_sensor: !input temperature_sensor
  setpoint: !input temperature_setpoint
  hyst: !input hysteresis
  module_type: !input module_type
  heating_entity_climate: !input heating_entity_climate
  heating_entity_select: !input heating_entity_select
  heating_entity: >
    {{ heating_entity_climate if module_type == 'Climate' else heating_entity_select }}
  heating_mode: !input heating_mode
  windows: !input window_sensors
  doors: !input door_sensors
  logic: !input sensor_logic
  room: !input room_name
  log_ent: !input log_entity
  
  # État des capteurs d'ouverture
  state_open: >
    {{ 'off' if logic == 'Inverse' else 'on' }}
  
  # VÉRIFICATION CRITIQUE : Y a-t-il un ouvrant ouvert ?
  any_open: >
    {% set all_sensors = (windows | default([])) + (doors | default([])) %}
    {% if all_sensors | length == 0 %}
      false
    {% else %}
      {{ expand(all_sensors) | selectattr('state','eq', state_open) | list | length > 0 }}
    {% endif %}
  
  # Température actuelle et consigne
  current_temp: >
    {{ states(temp_sensor) | float(0) }}
  target_temp: >
    {{ states(setpoint) | float(19) }}
  
  # Mode actuel du chauffage
  current_mode: >
    {% if module_type == 'Select' %}
      {{ states(heating_entity) }}
    {% else %}
      {{ state_attr(heating_entity, 'preset_mode') }}
    {% endif %}
  
  # Mapper les modes pour NodOn
  heating_mode_mapped: >
    {% set mode = heating_mode %}
    {{ 'comfort_-1' if mode == 'comfort-1' else 
       'comfort_-2' if mode == 'comfort-2' else mode }}

# ===== TRIGGERS =====
trigger:
  - platform: state
    entity_id: !input temperature_sensor
    id: temp_change
  
  - platform: state
    entity_id: !input temperature_setpoint
    id: setpoint_change
  
  - platform: state
    entity_id: !input thermostat_active
    id: active_change
  
  # Trigger sur ouverture fenêtre/porte
  - platform: state
    entity_id: !input window_sensors
    to: 
      - "on"
      - "off"
    id: window_change
  
  - platform: state
    entity_id: !input door_sensors
    to:
      - "on"
      - "off"
    id: door_change

condition: []

# ===== ACTIONS =====
action:
  - choose:
      # === THERMOSTAT DÉSACTIVÉ ===
      - conditions:
          - condition: template
            value_template: "{{ is_state(active, 'off') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ module_type == 'Select' }}"
                  - condition: template
                    value_template: "{{ current_mode not in ['off', 'none'] }}"
                sequence:
                  - service: select.select_option
                    target:
                      entity_id: "{{ heating_entity }}"
                    data:
                      option: "off"
              
              - conditions:
                  - condition: template
                    value_template: "{{ module_type == 'Climate' }}"
                  - condition: template
                    value_template: "{{ current_mode not in ['off', 'none'] }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: "{{ heating_entity }}"
          
          - if:
              - condition: template
                value_template: "{{ log_ent != '' }}"
            then:
              - service: input_text.set_value
                target:
                  entity_id: "{{ log_ent }}"
                data:
                  value: "{{ now().strftime('%H:%M') }} - {{ room }}: ⏸️ Thermostat DÉSACTIVÉ"

      # === OUVRANT OUVERT → SÉCURITÉ ===
      - conditions:
          - condition: template
            value_template: "{{ is_state(active, 'on') }}"
          - condition: template
            value_template: "{{ any_open }}"
        sequence:
          # Couper le chauffage si actuellement allumé
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ module_type == 'Select' }}"
                  - condition: template
                    value_template: "{{ current_mode not in ['off', 'none'] }}"
                sequence:
                  - service: select.select_option
                    target:
                      entity_id: "{{ heating_entity }}"
                    data:
                      option: "off"
                  
                  - if:
                      - condition: template
                        value_template: "{{ log_ent != '' }}"
                    then:
                      - service: input_text.set_value
                        target:
                          entity_id: "{{ log_ent }}"
                        data:
                          value: "{{ now().strftime('%H:%M') }} - {{ room }}: 🚨 SÉCURITÉ - Ouvrant ouvert, chauffage OFF"
              
              - conditions:
                  - condition: template
                    value_template: "{{ module_type == 'Climate' }}"
                  - condition: template
                    value_template: "{{ current_mode not in ['off', 'none'] }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: "{{ heating_entity }}"
                  
                  - if:
                      - condition: template
                        value_template: "{{ log_ent != '' }}"
                    then:
                      - service: input_text.set_value
                        target:
                          entity_id: "{{ log_ent }}"
                        data:
                          value: "{{ now().strftime('%H:%M') }} - {{ room }}: 🚨 SÉCURITÉ - Ouvrant ouvert, chauffage OFF"

      # === RÉGULATION NORMALE (Thermostat actif ET tout fermé) ===
      - conditions:
          - condition: template
            value_template: "{{ is_state(active, 'on') }}"
          - condition: template
            value_template: "{{ not any_open }}"
        sequence:
          - choose:
              # === TEMPÉRATURE TROP BASSE → CHAUFFER ===
              - conditions:
                  - condition: template
                    value_template: "{{ current_temp < (target_temp - hyst) }}"
                sequence:
                  # ⚠️ VÉRIFICATION FINALE DE SÉCURITÉ AVANT ALLUMAGE
                  - condition: template
                    value_template: "{{ not any_open }}"
                  
                  - choose:
                      # MODULE SELECT (NodOn)
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Select' }}"
                          - condition: template
                            value_template: "{{ current_mode != heating_mode_mapped }}"
                        sequence:
                          - service: select.select_option
                            target:
                              entity_id: "{{ heating_entity }}"
                            data:
                              option: "{{ heating_mode_mapped }}"
                          
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: 🔥 Chauffage ON ({{ current_temp | round(1) }}°C < {{ (target_temp - hyst) | round(1) }}°C)
                      
                      # MODULE CLIMATE
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Climate' }}"
                          - condition: template
                            value_template: "{{ current_mode != heating_mode }}"
                        sequence:
                          - service: climate.turn_on
                            target:
                              entity_id: "{{ heating_entity }}"
                          - service: climate.set_preset_mode
                            target:
                              entity_id: "{{ heating_entity }}"
                            data:
                              preset_mode: "{{ heating_mode }}"
                          
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: 🔥 Chauffage ON ({{ current_temp | round(1) }}°C < {{ (target_temp - hyst) | round(1) }}°C)

              # === TEMPÉRATURE TROP HAUTE → COUPER ===
              - conditions:
                  - condition: template
                    value_template: "{{ current_temp > (target_temp + 0.2) }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Select' }}"
                          - condition: template
                            value_template: "{{ current_mode not in ['off', 'none'] }}"
                        sequence:
                          - service: select.select_option
                            target:
                              entity_id: "{{ heating_entity }}"
                            data:
                              option: "off"
                          
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: ❄️ Chauffage OFF ({{ current_temp | round(1) }}°C > {{ (target_temp + 0.2) | round(1) }}°C)
                      
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Climate' }}"
                          - condition: template
                            value_template: "{{ current_mode not in ['off', 'none'] }}"
                        sequence:
                          - service: climate.turn_off
                            target:
                              entity_id: "{{ heating_entity }}"
                          
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: ❄️ Chauffage OFF ({{ current_temp | round(1) }}°C > {{ (target_temp + hyst) | round(1) }}°C)

mode: queued
max: 10
