blueprint:
  name: External Thermostat Control v1.1
  source_url: https://raw.githubusercontent.com/jcspenle/HA_SensorPilotWire/main/blueprints/automation/jcspenle/external_thermostat_control_light.yaml
  description: >
    Thermostat virtuel utilisant une sonde de température externe pour contrôler un chauffage fil pilote.
    
    **Version Light** : Gère UNIQUEMENT la régulation de température.
    Compatible avec le blueprint fenêtres/portes (séparation des responsabilités).
    
    Fonctionnalités :
    - Compatible Climate Entity (Zigbee/Z-Wave) et Select Fil Pilote (NodOn)
    - Hystérésis configurable (0.5°C recommandé pour radiateurs fonte)
    - Consigne de température ajustable via input_number
    - Activation/désactivation manuelle via input_boolean
    - Mode de chauffage configurable (comfort, eco, etc.)
    - Logs optionnels pour le suivi
    
    Note : Les fenêtres/portes doivent être gérées par le blueprint séparé "Heating Control - Window/Door Open Detection"
    pour éviter les conflits et assurer une architecture claire.
  domain: automation

  input:
    # === CONFIGURATION PRINCIPALE ===
    thermostat_active:
      name: Activation du thermostat
      description: Input boolean pour activer/désactiver le thermostat. Quand désactivé, le chauffage est forcé à OFF.
      selector:
        entity:
          domain: input_boolean

    temperature_sensor:
      name: Capteur de température
      description: Sonde de température externe à utiliser pour la régulation (différente de celle du chauffage)
      selector:
        entity:
          domain: sensor
          device_class: temperature

    temperature_setpoint:
      name: Consigne de température
      description: Input number contenant la température cible souhaitée
      selector:
        entity:
          domain: input_number

    hysteresis:
      name: Hystérésis
      description: Écart de température pour éviter les cycles rapides ON/OFF. Recommandation 0.5°C pour radiateurs fonte (bonne inertie).
      selector:
        number:
          min: 0.1
          max: 2.0
          step: 0.1
          unit_of_measurement: "°C"
      default: 0.5

    # === MODULE DE CHAUFFAGE ===
    module_type:
      name: Type de module chauffage
      description: "Climate: entité climate (Zigbee/Z-Wave/WiFi) | Select: entité select fil pilote (NodOn)"
      selector:
        select:
          options: ["Climate", "Select"]
      default: "Select"

    heating_entity_climate:
      name: Entité de chauffage (Climate)
      description: "Sélectionner l'entité climate si type Climate (laisser vide si type Select)"
      selector:
        entity:
          domain: climate
      default: ""

    heating_entity_select:
      name: Entité de chauffage (Select Fil Pilote)
      description: "Sélectionner l'entité select fil pilote si type Select/NodOn (laisser vide si type Climate)"
      selector:
        entity:
          domain: select
      default: ""

    heating_mode:
      name: Mode de chauffage actif
      description: Mode à utiliser quand le chauffage doit être actif (température trop basse)
      selector:
        select:
          options: ["comfort","comfort-1","comfort-2","eco"]
      default: "comfort"

    # === NOTIFICATIONS & LOGS ===
    room_name:
      name: Nom de la pièce
      description: Nom de la pièce pour l'identification dans les logs
      selector:
        text: {}
      default: "Pièce"

    log_entity:
      name: Entité de log (optionnel)
      description: Input_text pour logger l'activité du thermostat. Laisser vide pour désactiver les logs.
      selector:
        entity:
          domain: input_text
      default: ""

# ===== VARIABLES =====
variables:
  active: !input thermostat_active
  temp_sensor: !input temperature_sensor
  setpoint: !input temperature_setpoint
  hyst: !input hysteresis
  module_type: !input module_type
  heating_entity_climate: !input heating_entity_climate
  heating_entity_select: !input heating_entity_select
  heating_entity: >
    {{ heating_entity_climate if module_type == 'Climate' else heating_entity_select }}
  heating_mode: !input heating_mode
  room: !input room_name
  log_ent: !input log_entity
  
  # Température actuelle et consigne
  current_temp: >
    {{ states(temp_sensor) | float(0) }}
  target_temp: >
    {{ states(setpoint) | float(19) }}
  
  # Mode actuel du chauffage
  current_mode: >
    {% if module_type == 'Select' %}
      {{ states(heating_entity) }}
    {% else %}
      {{ state_attr(heating_entity, 'preset_mode') }}
    {% endif %}
  
  # Mapper les modes pour NodOn (comfort-1 → comfort_-1)
  heating_mode_mapped: >
    {% set mode = heating_mode %}
    {{ 'comfort_-1' if mode == 'comfort-1' else 
       'comfort_-2' if mode == 'comfort-2' else mode }}

# ===== TRIGGERS =====
trigger:
  # Changement de température
  - platform: state
    entity_id: !input temperature_sensor
    id: temp_change
  
  # Changement de consigne
  - platform: state
    entity_id: !input temperature_setpoint
    id: setpoint_change
  
  # Activation/désactivation manuelle
  - platform: state
    entity_id: !input thermostat_active
    id: active_change

# ===== CONDITIONS =====
condition: []

# ===== ACTIONS =====
action:
  - choose:
      # === THERMOSTAT DÉSACTIVÉ ===
      - conditions:
          - condition: template
            value_template: "{{ is_state(active, 'off') }}"
        sequence:
          # Si le chauffage est actuellement actif, le couper
          - choose:
              # MODULE SELECT (NodOn)
              - conditions:
                  - condition: template
                    value_template: "{{ module_type == 'Select' }}"
                  - condition: template
                    value_template: "{{ current_mode not in ['off', 'none'] }}"
                sequence:
                  - service: select.select_option
                    target:
                      entity_id: "{{ heating_entity }}"
                    data:
                      option: "off"
              
              # MODULE CLIMATE
              - conditions:
                  - condition: template
                    value_template: "{{ module_type == 'Climate' }}"
                  - condition: template
                    value_template: "{{ current_mode not in ['off', 'none'] }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: "{{ heating_entity }}"
          
          # Log de désactivation
          - if:
              - condition: template
                value_template: "{{ log_ent != '' }}"
            then:
              - service: input_text.set_value
                target:
                  entity_id: "{{ log_ent }}"
                data:
                  value: "{{ now().strftime('%H:%M') }} - {{ room }}: ⏸️ Thermostat DÉSACTIVÉ"

      # === RÉGULATION NORMALE (Thermostat actif) ===
      - conditions:
          - condition: template
            value_template: "{{ is_state(active, 'on') }}"
        sequence:
          - choose:
              # === TEMPÉRATURE TROP BASSE → CHAUFFER ===
              - conditions:
                  - condition: template
                    value_template: "{{ current_temp < (target_temp - hyst) }}"
                sequence:
                  # Activer le chauffage selon le type de module
                  - choose:
                      # MODULE SELECT (NodOn)
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Select' }}"
                          - condition: template
                            value_template: "{{ current_mode != heating_mode_mapped }}"
                        sequence:
                          - service: select.select_option
                            target:
                              entity_id: "{{ heating_entity }}"
                            data:
                              option: "{{ heating_mode_mapped }}"
                          
                          # Log activation
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: 🔥 Chauffage ON ({{ current_temp | round(1) }}°C < {{ (target_temp - hyst) | round(1) }}°C)
                      
                      # MODULE CLIMATE
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Climate' }}"
                          - condition: template
                            value_template: "{{ current_mode != heating_mode }}"
                        sequence:
                          - service: climate.turn_on
                            target:
                              entity_id: "{{ heating_entity }}"
                          - service: climate.set_preset_mode
                            target:
                              entity_id: "{{ heating_entity }}"
                            data:
                              preset_mode: "{{ heating_mode }}"
                          
                          # Log activation
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: 🔥 Chauffage ON ({{ current_temp | round(1) }}°C < {{ (target_temp - hyst) | round(1) }}°C)

              # === TEMPÉRATURE TROP HAUTE → COUPER ===
              - conditions:
                  - condition: template
                    value_template: "{{ current_temp > (target_temp + hyst) }}"
                sequence:
                  # Couper le chauffage selon le type de module
                  - choose:
                      # MODULE SELECT (NodOn)
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Select' }}"
                          - condition: template
                            value_template: "{{ current_mode not in ['off', 'none'] }}"
                        sequence:
                          - service: select.select_option
                            target:
                              entity_id: "{{ heating_entity }}"
                            data:
                              option: "off"
                          
                          # Log désactivation
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: ❄️ Chauffage OFF ({{ current_temp | round(1) }}°C > {{ (target_temp + hyst) | round(1) }}°C)
                      
                      # MODULE CLIMATE
                      - conditions:
                          - condition: template
                            value_template: "{{ module_type == 'Climate' }}"
                          - condition: template
                            value_template: "{{ current_mode not in ['off', 'none'] }}"
                        sequence:
                          - service: climate.turn_off
                            target:
                              entity_id: "{{ heating_entity }}"
                          
                          # Log désactivation
                          - if:
                              - condition: template
                                value_template: "{{ log_ent != '' }}"
                            then:
                              - service: input_text.set_value
                                target:
                                  entity_id: "{{ log_ent }}"
                                data:
                                  value: >
                                    {{ now().strftime('%H:%M') }} - {{ room }}: ❄️ Chauffage OFF ({{ current_temp | round(1) }}°C > {{ (target_temp + hyst) | round(1) }}°C)

              # === ZONE MORTE (entre target-hyst et target+hyst) ===
              # Pas d'action, on laisse le chauffage dans son état actuel pour éviter les cycles rapides

mode: queued
max: 10
